const db = require('./connection');

const selectAll = async (table) => {
  const [rows] = await db.query(`SELECT * FROM ${table} ORDER BY id`);
  return rows;
};

const selectById = async (table, id) => {
  const [rows] = await db.query(`SELECT * FROM ${table} WHERE id = ?`, [id]);
  return rows[0] || null;
};

const selectByField = async (table, field, value) => {
  const [rows] = await db.query(`SELECT * FROM ${table} WHERE ${field} = ? ORDER BY id`, [value]);
  return rows;
};

const selectLimited = async (table, limit, offset) => {
  const [rows] = await db.query(
    `SELECT * FROM ${table} ORDER BY id LIMIT ? OFFSET ?`,
    [parseInt(limit), parseInt(offset)]
  );
  return rows;
};

const updateRow = async (table, columns, values, id) => {
  const setClause = columns.map(c => `${c} = ?`).join(', ');
  await db.query(`UPDATE ${table} SET ${setClause} WHERE id = ?`, [...values, id]);
  return selectById(table, id);
};

const deleteRow = async (table, id) => {
  const [result] = await db.query(`DELETE FROM ${table} WHERE id = ?`, [id]);
  return result.affectedRows > 0;
};

const insertRowAutoId = async (table, columns, values) => {
  const cols = columns.join(', ');
  const placeholders = columns.map(() => '?').join(', ');
  const [result] = await db.query(`INSERT INTO ${table} (${cols}) VALUES (${placeholders})`, values);
  const autoGeneratedId = result.insertId;
  return selectById(table, autoGeneratedId);
};

const existsByFields = async (table, fieldMap) => {
  const conditions = Object.keys(fieldMap).map(k => `${k} = ?`).join(' AND ');
  const [rows] = await db.query(`SELECT id FROM ${table} WHERE ${conditions}`, Object.values(fieldMap));
  return rows.length > 0;
};

const updateByField = async (table, columns, values, whereField, whereValue) => {
  const setClause = columns.map(c => `${c} = ?`).join(', ');
  const [result] = await db.query(`UPDATE ${table} SET ${setClause} WHERE ${whereField} = ?`, [...values, whereValue]);
  return result.affectedRows > 0;
};

module.exports = { selectAll, selectById, selectByField, selectLimited, updateRow, deleteRow, insertRowAutoId, existsByFields, updateByField };
